### ISSUE TITLE
Seahub broken on Debian (raspbian) buster

### ISSUE THREAD

**Issue by k3an3** [haiwen/seafile-rpi#37]
The server starts fine on Debian buster. However, when making a request to the webserver, "Internal Server Error" is returned, and the following tracebacks generated due to changes in Python libraries:

```
2019-07-11 20:19:36,773 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api2/repos/
Traceback (most recent call last):
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/middleware/locale.py", line 24, in process_request
    i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
    for url_pattern in get_resolver(urlconf).url_patterns:
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/seafile-server-6.3.4/seahub/seahub/utils/rooturl.py", line 41, in <module>
    url(r'^%s' % settings.SITE_ROOT[1:], include(settings.SITE_ROOT_URLCONF)),
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/seafile-server-6.3.4/seahub/seahub/urls.py", line 12, in <module>
    from seahub.views.file import view_history_file, view_trash_file,\
  File "/var/www/seafile-server-6.3.4/seahub/seahub/views/file.py", line 41, in <module>
    from seahub.wopi.utils import get_wopi_dict
  File "/var/www/seafile-server-6.3.4/seahub/seahub/wopi/utils.py", line 7, in <module>
    import requests
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/requests-2.18.4-py2.7.egg/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/requests-2.18.4-py2.7.egg/requests/utils.py", line 24, in <module>
    from . import certs
ImportError: cannot import name certs
2019-07-11 20:19:39,575 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api2/starredfiles/
Traceback (most recent call last):
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/middleware/locale.py", line 24, in process_request
    i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
    for url_pattern in get_resolver(urlconf).url_patterns:
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/seafile-server-6.3.4/seahub/seahub/utils/rooturl.py", line 41, in <module>
    url(r'^%s' % settings.SITE_ROOT[1:], include(settings.SITE_ROOT_URLCONF)),
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/seafile-server-6.3.4/seahub/seahub/urls.py", line 12, in <module>
    from seahub.views.file import view_history_file, view_trash_file,\
  File "/var/www/seafile-server-6.3.4/seahub/seahub/views/file.py", line 41, in <module>
    from seahub.wopi.utils import get_wopi_dict
  File "/var/www/seafile-server-6.3.4/seahub/seahub/wopi/utils.py", line 7, in <module>
    import requests
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/requests-2.18.4-py2.7.egg/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/requests-2.18.4-py2.7.egg/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/requests-2.18.4-py2.7.egg/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/var/www/seafile-server-6.3.4/seahub/thirdpart/requests-2.18.4-py2.7.egg/requests/compat.py", line 47, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```
Not sure about the first error, which went away after updating the system's requests, but the second error is because of mismatches between the packaged version of requests and the system version of urllib3.

To temporarily fix this:

`sed -i 's/from urllib3.packages.ordered_dict import OrderedDict/from collections import OrderedDict/' /path/to/seahub/thirdpart/requests-2.18.4-py2.7.egg/requests/compat.py`

**Comment by jobenvil** [comment]
Could you try to install the properly `urllib3 `version? `pip install urllib3=1.22`

**Comment by jobenvil** [comment]
closed du to inactivite / feedback

**Comment by PirMei** [comment]
For closure: I had this exact problem when upgrading to Debian 10 (Buster) and uninstalling urllib3 1.24.1 and then installing urllib3 1.22 fixed it :+1: 
```
pip uninstall urllib3 && pip install urllib3==1.22
```
