### ISSUE TITLE
No module named defaults - SF 7.0.5

### ISSUE THREAD

**Issue by mims92** [haiwen/seafile-rpi#51]
Hello,

I have upgraded my seafile server from 6.0.0 to 7.0.5, did all the upgrade, etc.

When I try to access the seafile website, the message is: **Internal server error**.

Now, looking at the seahub log, I see this [1].
So it refers to `"/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/conf/urls/` which indeed does not contain any defaults module. I dug further in the code and saw that this was deprecated. 

Did I miss something?

Thank you

[1]
```
2020-02-16 19:37:30,678 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/middleware/locale.py", line 24, in process_request
    i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
    for url_pattern in get_resolver(urlconf).url_patterns:
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/seafile/seafile-server/seahub/seahub/utils/rooturl.py", line 41, in <module>
    url(r'^%s' % settings.SITE_ROOT[1:], include(settings.SITE_ROOT_URLCONF)),
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/seafile/seafile-server/seahub/seahub/urls.py", line 418, in <module>
    url(r'^captcha/', include('captcha.urls')),
  File "/home/seafile/seafile-server/seahub/thirdpart/Django-1.11.15-py2.7.egg/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/seafile/seafile-server/seahub/thirdpart/captcha/urls.py", line 4, in <module>
    from django.conf.urls.defaults import patterns, url
ImportError: No module named defaults
```

**Comment by thrynir** [comment]
Hi,

There something strange with your files. You have Django-1.11.15-py2.7.egg but in the release it's Django-1.11.16-py2.7.egg

Can you check you installed 7.0.5, and run minor_update.sh again ?

**Comment by mims92** [comment]
Hello, I downloaded 7.0.5 again and all works now... Sorry
