### ISSUE TITLE
cannot start seahub

### ISSUE THREAD

**Issue by kweonsunho** [haiwen/seafile-rpi#67]
./seahub.sh start-fastcgi

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub (fastcgi) at 127.0.0.1:8000 ...
Traceback (most recent call last):
  File "/var/www/seafile/seafile-server-7.1.4/seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/www/seafile/seafile-server-7.1.4/seahub/thirdpart/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/seafile/seafile-server-7.1.4/seahub/thirdpart/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/var/www/seafile/seafile-server-7.1.4/seahub/thirdpart/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/www/seafile/seafile-server-7.1.4/seahub/seahub/avatar/models.py", line 2, in <module>
    import _imaging
ImportError: No module named '_imaging'
Error:Seahub failed to start.
this error message.
What can I do?

**Comment by Gustl22** [comment]
Fastcgi is not supported! Only run `./seahub.sh`

To debug you can set `daemon = False` in `gunicorn.conf.py`

**Comment by netzeng** [comment]
i  am try,

this problem is solver!
thanks very much!!

**Comment by jobenvil** [comment]
@Gustl22 thanks!. Closing thread.
