### ISSUE TITLE
树莓派3B 安装seafile7.1.5提示缺少Image

### ISSUE THREAD

**Issue by hqs1** [haiwen/seafile-rpi#69]
`
pi@raspberrypi:~/seafile/seafile-server-7.1.5 $ sudo ./seahub.sh start-fastcgi

LC_ALL is not set in ENV, set to en_US.UTF-8
./seahub.sh: line 210: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Starting seahub (fastcgi) at 127.0.0.1:8000 ...
Traceback (most recent call last):
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/seahub/avatar/models.py", line 23, in <module>
    from PIL import Image
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/thirdpart/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/home/pi/seafile/seafile-server-7.1.5/seahub/thirdpart/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/thirdpart/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/thirdpart/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/thirdpart/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/thirdpart/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/thirdpart/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/seafile/seafile-server-7.1.5/seahub/seahub/avatar/models.py", line 26, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'
Error:Seahub failed to start.

Package        Version
-------------- ---------
asn1crypto     0.24.0
certifi        2018.8.24
chardet        3.0.4
configparser   3.5.0b2
crypto         1.4.1
cryptography   2.6.1
decorator      4.4.2
Django         1.11.29
entrypoints    0.3
enum34         1.1.6
futures        3.3.0
idna           2.6
image          1.5.33
imageio        2.4.1
ipaddress      1.0.17
keyring        17.1.1
keyrings.alt   3.1.1
moviepy        1.0.3
Naked          0.1.31
numpy          1.16.6
olefile        0.46
Pillow         6.2.2
pip            20.2.4
proglog        0.1.9
pyasn1         0.4.2
pyasn1-modules 0.2.1
pycrypto       2.6.1
PyGObject      3.30.4
pyOpenSSL      19.0.0
python-ldap    3.1.0
pytz           2020.4
pyxdg          0.25
PyYAML         5.3.1
requests       2.21.0
RPi.GPIO       0.7.0
SecretStorage  2.3.1
setuptools     44.1.1
shellescape    3.8.1
six            1.12.0
tqdm           4.52.0
urllib3        1.24.1
wheel          0.32.3
`

**Comment by Gustl22** [comment]
Fastcgi is not supported! Only run `./seahub.sh`

To debug you can set `daemon = False` in `gunicorn.conf.py`
