### ISSUE TITLE
8.03 server build works, but seahub won't start

### ISSUE THREAD

**Issue by nihilistaX** [haiwen/seafile-rpi#78]
Building 8.02 works really good thanks to the great buildscript, running fine here for some weeks.
Tried to build 8.03 server, that works but after that seahub won't start.
Seahub log shows data from my first try at 01-31, but not from today, curious...
Maybe i missed something? 
`Traceback (most recent call last):
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/seafile-server-8.0.3/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/root/seafile-server-8.0.3/seahub/seahub/views/__init__.py", line 1214, in react_fake_view
    'enable_share_to_department': settings.ENABLE_SHARE_TO_DEPARTMENT,
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/base.py", line 171, in render
    return self._render(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/webpack_loader/utils.py", line 64, in get_as_tags
    for chunk in bundle:
  File "/root/seafile-server-8.0.3/seahub/thirdpart/webpack_loader/utils.py", line 34, in _filter_by_extension
    for chunk in bundle:
  File "/root/seafile-server-8.0.3/seahub/thirdpart/webpack_loader/loader.py", line 45, in filter_chunks
    chunk['url'] = self.get_chunk_url(chunk)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/webpack_loader/loader.py", line 56, in get_chunk_url
    return staticfiles_storage.url(relpath)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/contrib/staticfiles/storage.py", line 153, in url
    return self._url(self.stored_name, name, force)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/contrib/staticfiles/storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "/root/seafile-server-8.0.3/seahub/thirdpart/django/contrib/staticfiles/storage.py", line 420, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'frontend/static/css/commons.chunk.css'
2021-01-31 11:34:02,686 [ERROR] django.request:228 log_response Internal Server Error: /favicon.ico`

**Comment by jobenvil** [comment]
Hi @nihilistaX this is commented here:
https://forum.seafile.com/t/broken-onlyoffice-in-seafile-ce-8-0-2/13564/21
you must take this requirements file:
https://github.com/jobenvil/rpi-build-seafile/blob/main/seahub_requirements_v8.0.3.txt

**Comment by nihilistaX** [comment]
OK, thx, i never used onlyoffice but i will try ;-)

**Comment by jobenvil** [comment]
@nihilistaX in the OnlyOffice article is mentioned why the compilation will not work if you use the `requirements.txt` file from the seahub (x64). You don't need to use OnlyOffice at all. Do you mind to close the issue after checking?

**Comment by nihilistaX** [comment]
Sure, tested it and now it works. Thanks to the great build script it was really easy to build a working sefile server now :-)
