### ISSUE TITLE
ubuntu 20.04 arm64 install 8.0.3 error NameError: name '_mysql' is not defined

### ISSUE THREAD

**Issue by williamnie** [haiwen/seafile-rpi#80]
my system info
1. python version: 3.8.5
2. system : ubuntu 20.04 arm64 server

error info
```
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: libmariadb.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-8.0.3/seahub/seahub/wsgi.py", line 25, in <module>
    application = get_wsgi_application()
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/contrib/sessions/models.py", line 1, in <module>
    from django.contrib.sessions.base_session import (
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/contrib/sessions/base_session.py", line 26, in <module>
    class AbstractBaseSession(models.Model):
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
Error:Seahub failed to start.
Please try to run "./seahub.sh start" again
```
please help me

**Comment by williamnie** [comment]
MySQLdb not support  Python3 ,so you should use pymysql
you need edit code. 
vim /seafile-server-8.0.3/seahub/seahub/__init__.py
```
import pymysql
pymysql.install_as_MySQLdb()
```
copy  seafile-server-7.1.5/seahub/thirdpart/pymysql  to seafile-server-8.0.3/seahub/thirdpart/

start seahub will success

**Comment by jobenvil** [comment]
> MySQLdb not support Python3 ,so you should use pymysql
> you need edit code.
> vim /seafile-server-8.0.3/seahub/seahub/**init**.py
> 
> ```
> import pymysql
> pymysql.install_as_MySQLdb()
> ```
> 
> copy seafile-server-7.1.5/seahub/thirdpart/pymysql to seafile-server-8.0.3/seahub/thirdpart/
> 
> start seahub will success

Revert to original config.
Then try this `python3 -m pip install PyMySQL` logged in as user seafile (or your seafile user).
later on: needs installation of dev client: `apt install libmysqlclient-dev` or `apt install libmariadbclient-dev`, choose your database type. One of these should do the trick. Let me know.

[Source](https://forum.seafile.com/t/seafile-server-8-0-3-for-raspberry-pi-is-ready-13-02-2021/13838/25)

**Comment by SpinningK** [comment]
ImportError: libmariadb.so.3: cannot open shared object file: No such file or directory

For this error, I solved it with:
`apt install libmariadb-dev`

**Comment by jobenvil** [comment]
@SpinningK [here in Forum](https://forum.seafile.com/t/seafile-server-8-0-3-for-raspberry-pi-is-ready-13-02-2021/13838/25)
